### ISSUE TITLE
Pytorch convert tools not working because libraries missing

### ISSUE THREAD

**Issue by jorgicio** [aclex/pytorch-ebuild#10]
Hi!

I tried your ebuild and it builds fine and pytorch module imports without any issue.
However, when I want to try any of the convert tools (onnx-to-caffe2 and caffe2-to-onnx), this happens:

``hackenherr ~ # convert-onnx-to-caffe2                                                                                                                                 [12:06:03]
Traceback (most recent call last):
  File "/usr/bin/convert-onnx-to-caffe2", line 11, in <module>
    load_entry_point('torch==1.5.0a0+3c31d73', 'console_scripts', 'convert-onnx-to-caffe2')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/caffe2/python/__init__.py", line 2, in <module>
    from caffe2.proto import caffe2_pb2
  File "/usr/lib/python3.7/site-packages/caffe2/proto/__init__.py", line 11, in <module>
    from caffe2.proto import caffe2_pb2, metanet_pb2, torch_pb2
ImportError: cannot import name 'caffe2_pb2' from 'caffe2.proto' (/usr/lib/python3.7/site-packages/caffe2/proto/__init__.py)

hackenherr ~ # convert-caffe2-to-onnx                                                                                                                                 [12:06:06]
Traceback (most recent call last):
  File "/usr/bin/convert-caffe2-to-onnx", line 11, in <module>
    load_entry_point('torch==1.5.0a0+3c31d73', 'console_scripts', 'convert-caffe2-to-onnx')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/caffe2/python/__init__.py", line 2, in <module>
    from caffe2.proto import caffe2_pb2
  File "/usr/lib/python3.7/site-packages/caffe2/proto/__init__.py", line 11, in <module>
    from caffe2.proto import caffe2_pb2, metanet_pb2, torch_pb2
ImportError: cannot import name 'caffe2_pb2' from 'caffe2.proto' (/usr/lib/python3.7/site-packages/caffe2/proto/__init__.py)
``

Tried both your ebuild as a based on the science overlay and the issue is the same.

May I miss something?

Thanks!

**Comment by aclex** [comment]
@jorgicio thanks for the detailed report! Honestly I haven't tested these tools that thoroughly. I'll look into this myself. Probably that's missing some dependency expecting it next to the script itself, as initially the scripts are installed in the wrong place and I have to move them manually. Will write here about any results.

**Comment by aclex** [comment]
@jorgicio I've just updated the 1.5.0 version of the ebuild with little fixes which copies the necessary Python bindings to Protobuf Caffe2 interface and to my little sanity check it fixes the problem with import. Unfortunately, I can't process it completely, as it requires not only ONNX model, but also some input tensor in some format, so no quick check here) Still I hope it works as expected now, check the `master` branch out, please. Thanks again for reporting it!

**Comment by jorgicio** [comment]
Yes, after trying, now it complains that onnx module is not found.

hackenherr ~ # convert-onnx-to-caffe2                                                                                              [18:16:28]
Traceback (most recent call last):
  File "/usr/bin/convert-onnx-to-caffe2", line 11, in <module>
    load_entry_point('torch==1.5.0a0+3c31d73', 'console_scripts', 'convert-onnx-to-caffe2')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/caffe2/python/onnx/bin/conversion.py", line 13, in <module>
    from onnx import checker, ModelProto
ModuleNotFoundError: No module named 'onnx'

Anyways, I don't know exactly what are those convert utils for.

Thanks for the fix :)

**Comment by aclex** [comment]
@jorgicio I think, you can cure it by simply installing the 'onnx' package, seems to be external dependency. As for the utilities, they seem to be quite dated and Caffe2-related, which is natural part of PyTorch now but not tend to be used directly anymore.

**Comment by jorgicio** [comment]
Mmm ok, I got it. That's weird because comparing with the package provided by Arch Linux (in the official repo), it doesn't require onnx. But anyways, it may solve this issue.

Thanks!

**Comment by jorgicio** [comment]
Hi!

I created a repo with the work you did with some reworks, and also tried it and I had to create the onnx package as a dependency for Pytorch.. Now it works without issues.

You can check it [here](https://github.com/jorgicio/pytorch-overlay) if you want it.

Thanks!

**Comment by aclex** [comment]
@jorgicio nice, thank you! Will look it through.
